# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        name: Server test
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - cd server
          - npm install
          - npm test
          - npm run lint
    - step:
        name: Client build and test
        caches: 
          - nodeclient
        script:
        - cd client
        - npm install
        - ng build
definitions:
  caches:
    node: server/node_modules
    nodeclient: client/node_modules