# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4

    working_directory: ~/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "client/package.json" }}
          - v1-dependencies-{{ checksum "server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
        name: Install packages in server
        command: |
          cd server
          npm i

      - run:
        name: Install  packages in client
        command: |
          cd client
          npm i

      - save_cache:
          paths:
            - client/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}
      
      - save_cache:
          paths:
            - server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}

      - run:
          name: Server test
          command: |
            cd server
            npm --version
            npm test

      - run:
          name: Server run lint
          command: |
            cd server
            npm run lint

      - run:
          name: Client build
          command: |
            cd client
            npm --version
            npm run-script build

      - run:
          name: Client run tests
          command: |
            cd client
            npm run-script pipeline

      - run:
          name: Client run tests
          command: |
            cd client
            npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build